security:
    # encryptage du mot de passe pour User
    encoders:
        App\Entity\User:
            algorithm: bcrypt



    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        db:
            #            LES UTILIS ST DES ENTITY USER
            entity:
                class: App\Entity\User
                #                L IDENTIFIANT EST L EMAIL
                property: email


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            #            ROUTE DE FORM DU LOGIN
            form_login:
                login_path: app_security_login
                check_path: app_security_login

            #                RTE DE LA PAGE DE DECONNEX
            logout:
                path: app_security_logout


            #            PROVIDER DEFINI AU DESSUS DS LA SECTION PROVIDERS
            provider: db

            #           SUR TT LE SITE
            pattern: ^/



            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
